console.log('components');

import './components/jquery-price-slider.js'
import './components/plugins.js'
import './components/bootstrap.min.js'
import './components/dbclick.min.js'
import './components/swipers.js'
import './components/jquery.countdown.min.js'
import './components/jquery.meanmenu.min.js'
import './components/jquery.scrollUp.min.js'
import './components/jquery.simpleGallery.min.js'
import './components/jquery.simpleLens.min.js'
import './components/owl.carousel.min.js'
import './components/popper.min.js'
import './components/main.js'
